### ISSUE TITLE
Get the build passing on Windows

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.AWS#3] opened 2016-10-24 20:52 UTC
I notice the build is failing on Windows https://github.com/mbraceproject/MBrace.AWS#build-status

**Comment by AviAvni** [comment] 2016-10-24 21:41
Can you trigger the build agian it's look like the problem is the package MathNet.Numerics not downloaded and the last build was 3 month ago on my machine the build.cmd downloaded this package 
i need aws credentials to run the test

**Comment by AviAvni** [comment] 2016-10-26 14:32
after you approved the PR of the README the build triggered and failed I checked it and the build failed because AppVeyor run msbuild on the solution and the packages
MathNet.Numerics
MathNet.Numerics.FSharp
MathNet.Numerics.MKL.Win-x64
only listed in the paket.dependencies file which restored only from the build.cmd/sh file
and not listed in any of the paket.references files in every projects in the VagabondTests.fs this packages are referenced  https://github.com/mbraceproject/MBrace.AWS/blob/master/tests/MBrace.AWS.Tests/VagabondTests.fs#L114-L115
in the linux the build run the build.sh so the packages downloaded

**Comment by eiriktsarpalis** [comment] 2016-11-02 00:44
Fixed in 2319a898759326e63049201cc1d710a7f7dcd764

**Closed by eiriktsarpalis** 2016-11-02 00:44 UTC
Labels: help wanted
